### ISSUE TITLE
Word rank after reveal

### ISSUE THREAD

**Issue by timonla** [local-minimum/wiki-reveal#47]
Would be nice to see the ranks for the words one did not guess in reveal mode. (Visibly different from the actually guessed words)

**Comment by local-minimum** [comment]
Implemented and included in next release:

![image](https://user-images.githubusercontent.com/8041100/187262615-1a465be2-c085-4feb-8b3f-135d83d195d9.png)
(From custom seed)

Not guessed words indicated by color and that the ordinal column has an N/A text.
